In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
from sklearn import model_selection
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression,Ridge,Lasso,ElasticNet
from sklearn.metrics import mean_squared_error,r2_score,accuracy_score,confusion_matrix
from sklearn.decomposition import PCA
from numpy import absolute
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RepeatedKFold
from xgboost import XGBRegressor





train_data=pd.read_csv('train2.csv')
test_data=pd.read_csv('test2.csv') 
print(train_data.shape, test_data.shape)

(4209, 378) (4209, 377)

In [2]:
train_data.head()

,ID,y,X0,X1,X2,X3,X4,X5,X6,X8,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
0,0,130.81,k,v,at,a,d,u,j,o,...,0,0,1,0,0,0,0,0,0,0
1,6,88.53,k,t,av,e,d,y,l,o,...,1,0,0,0,0,0,0,0,0,0
2,7,76.26,az,w,n,c,d,x,j,x,...,0,0,0,0,0,0,1,0,0,0
3,9,80.62,az,t,n,f,d,x,l,e,...,0,0,0,0,0,0,0,0,0,0
4,13,78.02,az,v,n,f,d,h,d,n,...,0,0,0,0,0,0,0,0,0,0

In [3]:
train_data.dtypes

ID        int64
y       float64
X0       object
X1       object
X2       object
         ...
X380      int64
X382      int64
X383      int64
X384      int64
X385      int64
Length: 378, dtype: object

In [4]:
train_data.info

<bound method DataFrame.info of         ID       y  X0 X1  X2 X3 X4  X5 X6 X8  ...  X375  X376  X377  X378  \
0        0  130.81   k  v  at  a  d   u  j  o  ...     0     0     1     0
1        6   88.53   k  t  av  e  d   y  l  o  ...     1     0     0     0
2        7   76.26  az  w   n  c  d   x  j  x  ...     0     0     0     0
3        9   80.62  az  t   n  f  d   x  l  e  ...     0     0     0     0
4       13   78.02  az  v   n  f  d   h  d  n  ...     0     0     0     0
...    ...     ...  .. ..  .. .. ..  .. .. ..  ...   ...   ...   ...   ...
4204  8405  107.39  ak  s  as  c  d  aa  d  q  ...     1     0     0     0
4205  8406  108.77   j  o   t  d  d  aa  h  h  ...     0     1     0     0
4206  8412  109.22  ak  v   r  a  d  aa  g  e  ...     0     0     1     0
4207  8415   87.48  al  r   e  f  d  aa  l  u  ...     0     0     0     0
4208  8417  110.85   z  r  ae  c  d  aa  g  w  ...     1     0     0     0

      X379  X380  X382  X383  X384  X385
0        0     0     0     0     0     0
1        0     0     0     0     0     0
2        0     0     1     0     0     0
3        0     0     0     0     0     0
4        0     0     0     0     0     0
...    ...   ...   ...   ...   ...   ...
4204     0     0     0     0     0     0
4205     0     0     0     0     0     0
4206     0     0     0     0     0     0
4207     0     0     0     0     0     0
4208     0     0     0     0     0     0

[4209 rows x 378 columns]>

In [5]:
train_data.describe()

,ID,y,X10,X11,X12,X13,X14,X15,X16,X17,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
count,4209.000000,4209.000000,4209.000000,4209.0,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,...,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000
mean,4205.960798,100.669318,0.013305,0.0,0.075077,0.057971,0.428130,0.000475,0.002613,0.007603,...,0.318841,0.057258,0.314802,0.020670,0.009503,0.008078,0.007603,0.001663,0.000475,0.001426
std,2437.608688,12.679381,0.114590,0.0,0.263547,0.233716,0.494867,0.021796,0.051061,0.086872,...,0.466082,0.232363,0.464492,0.142294,0.097033,0.089524,0.086872,0.040752,0.021796,0.037734
min,0.000000,72.110000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2095.000000,90.820000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,4220.000000,99.150000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,6314.000000,109.010000,0.000000,0.0,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,...,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,8417.000000,265.320000,1.000000,0.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [6]:
test_data.head()

,ID,X0,X1,X2,X3,X4,X5,X6,X8,X10,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
0,1,az,v,n,f,d,t,a,w,0,...,0,0,0,1,0,0,0,0,0,0
1,2,t,b,ai,a,d,b,g,y,0,...,0,0,1,0,0,0,0,0,0,0
2,3,az,v,as,f,d,a,j,j,0,...,0,0,0,1,0,0,0,0,0,0
3,4,az,l,n,f,d,z,l,n,0,...,0,0,0,1,0,0,0,0,0,0
4,5,w,s,as,c,d,y,i,m,0,...,1,0,0,0,0,0,0,0,0,0

In [7]:
test_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4209 entries, 0 to 4208
Columns: 377 entries, ID to X385
dtypes: int64(369), object(8)
memory usage: 12.1+ MB

In [8]:
train_data.isna().sum()

ID      0
y       0
X0      0
X1      0
X2      0
       ..
X380    0
X382    0
X383    0
X384    0
X385    0
Length: 378, dtype: int64

In [9]:
test_data.isna().sum()

ID      0
X0      0
X1      0
X2      0
X3      0
       ..
X380    0
X382    0
X383    0
X384    0
X385    0
Length: 377, dtype: int64

In [10]:
test_data.dtypes

ID       int64
X0      object
X1      object
X2      object
X3      object
         ...
X380     int64
X382     int64
X383     int64
X384     int64
X385     int64
Length: 377, dtype: object

In [11]:
train_data.columns

Index(['ID', 'y', 'X0', 'X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X8',
       ...
       'X375', 'X376', 'X377', 'X378', 'X379', 'X380', 'X382', 'X383', 'X384',
       'X385'],
      dtype='object', length=378)

In [12]:
test_data.columns

Index(['ID', 'X0', 'X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X8', 'X10',
       ...
       'X375', 'X376', 'X377', 'X378', 'X379', 'X380', 'X382', 'X383', 'X384',
       'X385'],
      dtype='object', length=377)

In [13]:
out=train_data.loc[:,train_data.nunique()!=1]
train_data

,ID,y,X0,X1,X2,X3,X4,X5,X6,X8,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
0,0,130.81,k,v,at,a,d,u,j,o,...,0,0,1,0,0,0,0,0,0,0
1,6,88.53,k,t,av,e,d,y,l,o,...,1,0,0,0,0,0,0,0,0,0
2,7,76.26,az,w,n,c,d,x,j,x,...,0,0,0,0,0,0,1,0,0,0
3,9,80.62,az,t,n,f,d,x,l,e,...,0,0,0,0,0,0,0,0,0,0
4,13,78.02,az,v,n,f,d,h,d,n,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4204,8405,107.39,ak,s,as,c,d,aa,d,q,...,1,0,0,0,0,0,0,0,0,0
4205,8406,108.77,j,o,t,d,d,aa,h,h,...,0,1,0,0,0,0,0,0,0,0
4206,8412,109.22,ak,v,r,a,d,aa,g,e,...,0,0,1,0,0,0,0,0,0,0
4207,8415,87.48,al,r,e,f,d,aa,l,u,...,0,0,0,0,0,0,0,0,0,0
4208,8417,110.85,z,r,ae,c,d,aa,g,w,...,1,0,0,0,0,0,0,0,0,0

In [14]:
out=test_data.loc[:,test_data.nunique()!=1]
test_data

,ID,X0,X1,X2,X3,X4,X5,X6,X8,X10,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
0,1,az,v,n,f,d,t,a,w,0,...,0,0,0,1,0,0,0,0,0,0
1,2,t,b,ai,a,d,b,g,y,0,...,0,0,1,0,0,0,0,0,0,0
2,3,az,v,as,f,d,a,j,j,0,...,0,0,0,1,0,0,0,0,0,0
3,4,az,l,n,f,d,z,l,n,0,...,0,0,0,1,0,0,0,0,0,0
4,5,w,s,as,c,d,y,i,m,0,...,1,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4204,8410,aj,h,as,f,d,aa,j,e,0,...,0,0,0,0,0,0,0,0,0,0
4205,8411,t,aa,ai,d,d,aa,j,y,0,...,0,1,0,0,0,0,0,0,0,0
4206,8413,y,v,as,f,d,aa,d,w,0,...,0,0,0,0,0,0,0,0,0,0
4207,8414,ak,v,as,a,d,aa,c,q,0,...,0,0,1,0,0,0,0,0,0,0
4208,8416,t,aa,ai,c,d,aa,g,r,0,...,1,0,0,0,0,0,0,0,0,0

In [15]:
for i in train_data.columns:
    print("Number of unique values in {} \n The unique values are {}".format(i,len(train_data[i].unique()),train_data[i].unique()))

Number of unique values in ID
 The unique values are 4209
Number of unique values in y
 The unique values are 2545
Number of unique values in X0
 The unique values are 47
Number of unique values in X1
 The unique values are 27
Number of unique values in X2
 The unique values are 44
Number of unique values in X3
 The unique values are 7
Number of unique values in X4
 The unique values are 4
Number of unique values in X5
 The unique values are 29
Number of unique values in X6
 The unique values are 12
Number of unique values in X8
 The unique values are 25
Number of unique values in X10
 The unique values are 2
Number of unique values in X11
 The unique values are 1
Number of unique values in X12
 The unique values are 2
Number of unique values in X13
 The unique values are 2
Number of unique values in X14
 The unique values are 2
Number of unique values in X15
 The unique values are 2
Number of unique values in X16
 The unique values are 2
Number of unique values in X17
 The unique values are 2
Number of unique values in X18
 The unique values are 2
Number of unique values in X19
 The unique values are 2
Number of unique values in X20
 The unique values are 2
Number of unique values in X21
 The unique values are 2
Number of unique values in X22
 The unique values are 2
Number of unique values in X23
 The unique values are 2
Number of unique values in X24
 The unique values are 2
Number of unique values in X26
 The unique values are 2
Number of unique values in X27
 The unique values are 2
Number of unique values in X28
 The unique values are 2
Number of unique values in X29
 The unique values are 2
Number of unique values in X30
 The unique values are 2
Number of unique values in X31
 The unique values are 2
Number of unique values in X32
 The unique values are 2
Number of unique values in X33
 The unique values are 2
Number of unique values in X34
 The unique values are 2
Number of unique values in X35
 The unique values are 2
Number of unique values in X36
 The unique values are 2
Number of unique values in X37
 The unique values are 2
Number of unique values in X38
 The unique values are 2
Number of unique values in X39
 The unique values are 2
Number of unique values in X40
 The unique values are 2
Number of unique values in X41
 The unique values are 2
Number of unique values in X42
 The unique values are 2
Number of unique values in X43
 The unique values are 2
Number of unique values in X44
 The unique values are 2
Number of unique values in X45
 The unique values are 2
Number of unique values in X46
 The unique values are 2
Number of unique values in X47
 The unique values are 2
Number of unique values in X48
 The unique values are 2
Number of unique values in X49
 The unique values are 2
Number of unique values in X50
 The unique values are 2
Number of unique values in X51
 The unique values are 2
Number of unique values in X52
 The unique values are 2
Number of unique values in X53
 The unique values are 2
Number of unique values in X54
 The unique values are 2
Number of unique values in X55
 The unique values are 2
Number of unique values in X56
 The unique values are 2
Number of unique values in X57
 The unique values are 2
Number of unique values in X58
 The unique values are 2
Number of unique values in X59
 The unique values are 2
Number of unique values in X60
 The unique values are 2
Number of unique values in X61
 The unique values are 2
Number of unique values in X62
 The unique values are 2
Number of unique values in X63
 The unique values are 2
Number of unique values in X64
 The unique values are 2
Number of unique values in X65
 The unique values are 2
Number of unique values in X66
 The unique values are 2
Number of unique values in X67
 The unique values are 2
Number of unique values in X68
 The unique values are 2
Number of unique values in X69
 The unique values are 2
Number of unique values in X70
 The unique values are 2
Number of unique values in X71
 The unique values are 2
Number of unique values in X73
 The unique values are 2
Number of unique values in X74
 The unique values are 2
Number of unique values in X75
 The unique values are 2
Number of unique values in X76
 The unique values are 2
Number of unique values in X77
 The unique values are 2
Number of unique values in X78
 The unique values are 2
Number of unique values in X79
 The unique values are 2
Number of unique values in X80
 The unique values are 2
Number of unique values in X81
 The unique values are 2
Number of unique values in X82
 The unique values are 2
Number of unique values in X83
 The unique values are 2
Number of unique values in X84
 The unique values are 2
Number of unique values in X85
 The unique values are 2
Number of unique values in X86
 The unique values are 2
Number of unique values in X87
 The unique values are 2
Number of unique values in X88
 The unique values are 2
Number of unique values in X89
 The unique values are 2
Number of unique values in X90
 The unique values are 2
Number of unique values in X91
 The unique values are 2
Number of unique values in X92
 The unique values are 2
Number of unique values in X93
 The unique values are 1
Number of unique values in X94
 The unique values are 2
Number of unique values in X95
 The unique values are 2
Number of unique values in X96
 The unique values are 2
Number of unique values in X97
 The unique values are 2
Number of unique values in X98
 The unique values are 2
Number of unique values in X99
 The unique values are 2
Number of unique values in X100
 The unique values are 2
Number of unique values in X101
 The unique values are 2
Number of unique values in X102
 The unique values are 2
Number of unique values in X103
 The unique values are 2
Number of unique values in X104
 The unique values are 2
Number of unique values in X105
 The unique values are 2
Number of unique values in X106
 The unique values are 2
Number of unique values in X107
 The unique values are 1
Number of unique values in X108
 The unique values are 2
Number of unique values in X109
 The unique values are 2
Number of unique values in X110
 The unique values are 2
Number of unique values in X111
 The unique values are 2
Number of unique values in X112
 The unique values are 2
Number of unique values in X113
 The unique values are 2
Number of unique values in X114
 The unique values are 2
Number of unique values in X115
 The unique values are 2
Number of unique values in X116
 The unique values are 2
Number of unique values in X117
 The unique values are 2
Number of unique values in X118
 The unique values are 2
Number of unique values in X119
 The unique values are 2
Number of unique values in X120
 The unique values are 2
Number of unique values in X122
 The unique values are 2
Number of unique values in X123
 The unique values are 2
Number of unique values in X124
 The unique values are 2
Number of unique values in X125
 The unique values are 2
Number of unique values in X126
 The unique values are 2
Number of unique values in X127
 The unique values are 2
Number of unique values in X128
 The unique values are 2
Number of unique values in X129
 The unique values are 2
Number of unique values in X130
 The unique values are 2
Number of unique values in X131
 The unique values are 2
Number of unique values in X132
 The unique values are 2
Number of unique values in X133
 The unique values are 2
Number of unique values in X134
 The unique values are 2
Number of unique values in X135
 The unique values are 2
Number of unique values in X136
 The unique values are 2
Number of unique values in X137
 The unique values are 2
Number of unique values in X138
 The unique values are 2
Number of unique values in X139
 The unique values are 2
Number of unique values in X140
 The unique values are 2
Number of unique values in X141
 The unique values are 2
Number of unique values in X142
 The unique values are 2
Number of unique values in X143
 The unique values are 2
Number of unique values in X144
 The unique values are 2
Number of unique values in X145
 The unique values are 2
Number of unique values in X146
 The unique values are 2
Number of unique values in X147
 The unique values are 2
Number of unique values in X148
 The unique values are 2
Number of unique values in X150
 The unique values are 2
Number of unique values in X151
 The unique values are 2
Number of unique values in X152
 The unique values are 2
Number of unique values in X153
 The unique values are 2
Number of unique values in X154
 The unique values are 2
Number of unique values in X155
 The unique values are 2
Number of unique values in X156
 The unique values are 2
Number of unique values in X157
 The unique values are 2
Number of unique values in X158
 The unique values are 2
Number of unique values in X159
 The unique values are 2
Number of unique values in X160
 The unique values are 2
Number of unique values in X161
 The unique values are 2
Number of unique values in X162
 The unique values are 2
Number of unique values in X163
 The unique values are 2
Number of unique values in X164
 The unique values are 2
Number of unique values in X165
 The unique values are 2
Number of unique values in X166
 The unique values are 2
Number of unique values in X167
 The unique values are 2
Number of unique values in X168
 The unique values are 2
Number of unique values in X169
 The unique values are 2
Number of unique values in X170
 The unique values are 2
Number of unique values in X171
 The unique values are 2
Number of unique values in X172
 The unique values are 2
Number of unique values in X173
 The unique values are 2
Number of unique values in X174
 The unique values are 2
Number of unique values in X175
 The unique values are 2
Number of unique values in X176
 The unique values are 2
Number of unique values in X177
 The unique values are 2
Number of unique values in X178
 The unique values are 2
Number of unique values in X179
 The unique values are 2
Number of unique values in X180
 The unique values are 2
Number of unique values in X181
 The unique values are 2
Number of unique values in X182
 The unique values are 2
Number of unique values in X183
 The unique values are 2
Number of unique values in X184
 The unique values are 2
Number of unique values in X185
 The unique values are 2
Number of unique values in X186
 The unique values are 2
Number of unique values in X187
 The unique values are 2
Number of unique values in X189
 The unique values are 2
Number of unique values in X190
 The unique values are 2
Number of unique values in X191
 The unique values are 2
Number of unique values in X192
 The unique values are 2
Number of unique values in X194
 The unique values are 2
Number of unique values in X195
 The unique values are 2
Number of unique values in X196
 The unique values are 2
Number of unique values in X197
 The unique values are 2
Number of unique values in X198
 The unique values are 2
Number of unique values in X199
 The unique values are 2
Number of unique values in X200
 The unique values are 2
Number of unique values in X201
 The unique values are 2
Number of unique values in X202
 The unique values are 2
Number of unique values in X203
 The unique values are 2
Number of unique values in X204
 The unique values are 2
Number of unique values in X205
 The unique values are 2
Number of unique values in X206
 The unique values are 2
Number of unique values in X207
 The unique values are 2
Number of unique values in X208
 The unique values are 2
Number of unique values in X209
 The unique values are 2
Number of unique values in X210
 The unique values are 2
Number of unique values in X211
 The unique values are 2
Number of unique values in X212
 The unique values are 2
Number of unique values in X213
 The unique values are 2
Number of unique values in X214
 The unique values are 2
Number of unique values in X215
 The unique values are 2
Number of unique values in X216
 The unique values are 2
Number of unique values in X217
 The unique values are 2
Number of unique values in X218
 The unique values are 2
Number of unique values in X219
 The unique values are 2
Number of unique values in X220
 The unique values are 2
Number of unique values in X221
 The unique values are 2
Number of unique values in X222
 The unique values are 2
Number of unique values in X223
 The unique values are 2
Number of unique values in X224
 The unique values are 2
Number of unique values in X225
 The unique values are 2
Number of unique values in X226
 The unique values are 2
Number of unique values in X227
 The unique values are 2
Number of unique values in X228
 The unique values are 2
Number of unique values in X229
 The unique values are 2
Number of unique values in X230
 The unique values are 2
Number of unique values in X231
 The unique values are 2
Number of unique values in X232
 The unique values are 2
Number of unique values in X233
 The unique values are 1
Number of unique values in X234
 The unique values are 2
Number of unique values in X235
 The unique values are 1
Number of unique values in X236
 The unique values are 2
Number of unique values in X237
 The unique values are 2
Number of unique values in X238
 The unique values are 2
Number of unique values in X239
 The unique values are 2
Number of unique values in X240
 The unique values are 2
Number of unique values in X241
 The unique values are 2
Number of unique values in X242
 The unique values are 2
Number of unique values in X243
 The unique values are 2
Number of unique values in X244
 The unique values are 2
Number of unique values in X245
 The unique values are 2
Number of unique values in X246
 The unique values are 2
Number of unique values in X247
 The unique values are 2
Number of unique values in X248
 The unique values are 2
Number of unique values in X249
 The unique values are 2
Number of unique values in X250
 The unique values are 2
Number of unique values in X251
 The unique values are 2
Number of unique values in X252
 The unique values are 2
Number of unique values in X253
 The unique values are 2
Number of unique values in X254
 The unique values are 2
Number of unique values in X255
 The unique values are 2
Number of unique values in X256
 The unique values are 2
Number of unique values in X257
 The unique values are 2
Number of unique values in X258
 The unique values are 2
Number of unique values in X259
 The unique values are 2
Number of unique values in X260
 The unique values are 2
Number of unique values in X261
 The unique values are 2
Number of unique values in X262
 The unique values are 2
Number of unique values in X263
 The unique values are 2
Number of unique values in X264
 The unique values are 2
Number of unique values in X265
 The unique values are 2
Number of unique values in X266
 The unique values are 2
Number of unique values in X267
 The unique values are 2
Number of unique values in X268
 The unique values are 1
Number of unique values in X269
 The unique values are 2
Number of unique values in X270
 The unique values are 2
Number of unique values in X271
 The unique values are 2
Number of unique values in X272
 The unique values are 2
Number of unique values in X273
 The unique values are 2
Number of unique values in X274
 The unique values are 2
Number of unique values in X275
 The unique values are 2
Number of unique values in X276
 The unique values are 2
Number of unique values in X277
 The unique values are 2
Number of unique values in X278
 The unique values are 2
Number of unique values in X279
 The unique values are 2
Number of unique values in X280
 The unique values are 2
Number of unique values in X281
 The unique values are 2
Number of unique values in X282
 The unique values are 2
Number of unique values in X283
 The unique values are 2
Number of unique values in X284
 The unique values are 2
Number of unique values in X285
 The unique values are 2
Number of unique values in X286
 The unique values are 2
Number of unique values in X287
 The unique values are 2
Number of unique values in X288
 The unique values are 2
Number of unique values in X289
 The unique values are 1
Number of unique values in X290
 The unique values are 1
Number of unique values in X291
 The unique values are 2
Number of unique values in X292
 The unique values are 2
Number of unique values in X293
 The unique values are 1
Number of unique values in X294
 The unique values are 2
Number of unique values in X295
 The unique values are 2
Number of unique values in X296
 The unique values are 2
Number of unique values in X297
 The unique values are 1
Number of unique values in X298
 The unique values are 2
Number of unique values in X299
 The unique values are 2
Number of unique values in X300
 The unique values are 2
Number of unique values in X301
 The unique values are 2
Number of unique values in X302
 The unique values are 2
Number of unique values in X304
 The unique values are 2
Number of unique values in X305
 The unique values are 2
Number of unique values in X306
 The unique values are 2
Number of unique values in X307
 The unique values are 2
Number of unique values in X308
 The unique values are 2
Number of unique values in X309
 The unique values are 2
Number of unique values in X310
 The unique values are 2
Number of unique values in X311
 The unique values are 2
Number of unique values in X312
 The unique values are 2
Number of unique values in X313
 The unique values are 2
Number of unique values in X314
 The unique values are 2
Number of unique values in X315
 The unique values are 2
Number of unique values in X316
 The unique values are 2
Number of unique values in X317
 The unique values are 2
Number of unique values in X318
 The unique values are 2
Number of unique values in X319
 The unique values are 2
Number of unique values in X320
 The unique values are 2
Number of unique values in X321
 The unique values are 2
Number of unique values in X322
 The unique values are 2
Number of unique values in X323
 The unique values are 2
Number of unique values in X324
 The unique values are 2
Number of unique values in X325
 The unique values are 2
Number of unique values in X326
 The unique values are 2
Number of unique values in X327
 The unique values are 2
Number of unique values in X328
 The unique values are 2
Number of unique values in X329
 The unique values are 2
Number of unique values in X330
 The unique values are 1
Number of unique values in X331
 The unique values are 2
Number of unique values in X332
 The unique values are 2
Number of unique values in X333
 The unique values are 2
Number of unique values in X334
 The unique values are 2
Number of unique values in X335
 The unique values are 2
Number of unique values in X336
 The unique values are 2
Number of unique values in X337
 The unique values are 2
Number of unique values in X338
 The unique values are 2
Number of unique values in X339
 The unique values are 2
Number of unique values in X340
 The unique values are 2
Number of unique values in X341
 The unique values are 2
Number of unique values in X342
 The unique values are 2
Number of unique values in X343
 The unique values are 2
Number of unique values in X344
 The unique values are 2
Number of unique values in X345
 The unique values are 2
Number of unique values in X346
 The unique values are 2
Number of unique values in X347
 The unique values are 1
Number of unique values in X348
 The unique values are 2
Number of unique values in X349
 The unique values are 2
Number of unique values in X350
 The unique values are 2
Number of unique values in X351
 The unique values are 2
Number of unique values in X352
 The unique values are 2
Number of unique values in X353
 The unique values are 2
Number of unique values in X354
 The unique values are 2
Number of unique values in X355
 The unique values are 2
Number of unique values in X356
 The unique values are 2
Number of unique values in X357
 The unique values are 2
Number of unique values in X358
 The unique values are 2
Number of unique values in X359

In [16]:
for i in test_data.columns:
    print("Number of unique values in {} \n The unique values are {}".format(i,len(test_data[i].unique()),test_data[i].unique()))

Number of unique values in ID
 The unique values are 4209
Number of unique values in X0
 The unique values are 49
Number of unique values in X1
 The unique values are 27
Number of unique values in X2
 The unique values are 45
Number of unique values in X3
 The unique values are 7
Number of unique values in X4
 The unique values are 4
Number of unique values in X5
 The unique values are 32
Number of unique values in X6
 The unique values are 12
Number of unique values in X8
 The unique values are 25
Number of unique values in X10
 The unique values are 2
Number of unique values in X11
 The unique values are 2
Number of unique values in X12
 The unique values are 2
Number of unique values in X13
 The unique values are 2
Number of unique values in X14
 The unique values are 2
Number of unique values in X15
 The unique values are 2
Number of unique values in X16
 The unique values are 2
Number of unique values in X17
 The unique values are 2
Number of unique values in X18
 The unique values are 2
Number of unique values in X19
 The unique values are 2
Number of unique values in X20
 The unique values are 2
Number of unique values in X21
 The unique values are 2
Number of unique values in X22
 The unique values are 2
Number of unique values in X23
 The unique values are 2
Number of unique values in X24
 The unique values are 2
Number of unique values in X26
 The unique values are 2
Number of unique values in X27
 The unique values are 2
Number of unique values in X28
 The unique values are 2
Number of unique values in X29
 The unique values are 2
Number of unique values in X30
 The unique values are 2
Number of unique values in X31
 The unique values are 2
Number of unique values in X32
 The unique values are 2
Number of unique values in X33
 The unique values are 2
Number of unique values in X34
 The unique values are 2
Number of unique values in X35
 The unique values are 2
Number of unique values in X36
 The unique values are 2
Number of unique values in X37
 The unique values are 2
Number of unique values in X38
 The unique values are 2
Number of unique values in X39
 The unique values are 2
Number of unique values in X40
 The unique values are 2
Number of unique values in X41
 The unique values are 2
Number of unique values in X42
 The unique values are 2
Number of unique values in X43
 The unique values are 2
Number of unique values in X44
 The unique values are 2
Number of unique values in X45
 The unique values are 2
Number of unique values in X46
 The unique values are 2
Number of unique values in X47
 The unique values are 2
Number of unique values in X48
 The unique values are 2
Number of unique values in X49
 The unique values are 2
Number of unique values in X50
 The unique values are 2
Number of unique values in X51
 The unique values are 2
Number of unique values in X52
 The unique values are 2
Number of unique values in X53
 The unique values are 2
Number of unique values in X54
 The unique values are 2
Number of unique values in X55
 The unique values are 2
Number of unique values in X56
 The unique values are 2
Number of unique values in X57
 The unique values are 2
Number of unique values in X58
 The unique values are 2
Number of unique values in X59
 The unique values are 2
Number of unique values in X60
 The unique values are 2
Number of unique values in X61
 The unique values are 2
Number of unique values in X62
 The unique values are 2
Number of unique values in X63
 The unique values are 2
Number of unique values in X64
 The unique values are 2
Number of unique values in X65
 The unique values are 2
Number of unique values in X66
 The unique values are 2
Number of unique values in X67
 The unique values are 2
Number of unique values in X68
 The unique values are 2
Number of unique values in X69
 The unique values are 2
Number of unique values in X70
 The unique values are 2
Number of unique values in X71
 The unique values are 2
Number of unique values in X73
 The unique values are 2
Number of unique values in X74
 The unique values are 2
Number of unique values in X75
 The unique values are 2
Number of unique values in X76
 The unique values are 2
Number of unique values in X77
 The unique values are 2
Number of unique values in X78
 The unique values are 2
Number of unique values in X79
 The unique values are 2
Number of unique values in X80
 The unique values are 2
Number of unique values in X81
 The unique values are 2
Number of unique values in X82
 The unique values are 2
Number of unique values in X83
 The unique values are 2
Number of unique values in X84
 The unique values are 2
Number of unique values in X85
 The unique values are 2
Number of unique values in X86
 The unique values are 2
Number of unique values in X87
 The unique values are 2
Number of unique values in X88
 The unique values are 2
Number of unique values in X89
 The unique values are 2
Number of unique values in X90
 The unique values are 2
Number of unique values in X91
 The unique values are 2
Number of unique values in X92
 The unique values are 2
Number of unique values in X93
 The unique values are 2
Number of unique values in X94
 The unique values are 2
Number of unique values in X95
 The unique values are 2
Number of unique values in X96
 The unique values are 2
Number of unique values in X97
 The unique values are 2
Number of unique values in X98
 The unique values are 2
Number of unique values in X99
 The unique values are 2
Number of unique values in X100
 The unique values are 2
Number of unique values in X101
 The unique values are 2
Number of unique values in X102
 The unique values are 2
Number of unique values in X103
 The unique values are 2
Number of unique values in X104
 The unique values are 2
Number of unique values in X105
 The unique values are 2
Number of unique values in X106
 The unique values are 2
Number of unique values in X107
 The unique values are 2
Number of unique values in X108
 The unique values are 2
Number of unique values in X109
 The unique values are 2
Number of unique values in X110
 The unique values are 2
Number of unique values in X111
 The unique values are 2
Number of unique values in X112
 The unique values are 2
Number of unique values in X113
 The unique values are 2
Number of unique values in X114
 The unique values are 2
Number of unique values in X115
 The unique values are 2
Number of unique values in X116
 The unique values are 2
Number of unique values in X117
 The unique values are 2
Number of unique values in X118
 The unique values are 2
Number of unique values in X119
 The unique values are 2
Number of unique values in X120
 The unique values are 2
Number of unique values in X122
 The unique values are 2
Number of unique values in X123
 The unique values are 2
Number of unique values in X124
 The unique values are 2
Number of unique values in X125
 The unique values are 2
Number of unique values in X126
 The unique values are 2
Number of unique values in X127
 The unique values are 2
Number of unique values in X128
 The unique values are 2
Number of unique values in X129
 The unique values are 2
Number of unique values in X130
 The unique values are 2
Number of unique values in X131
 The unique values are 2
Number of unique values in X132
 The unique values are 2
Number of unique values in X133
 The unique values are 2
Number of unique values in X134
 The unique values are 2
Number of unique values in X135
 The unique values are 2
Number of unique values in X136
 The unique values are 2
Number of unique values in X137
 The unique values are 2
Number of unique values in X138
 The unique values are 2
Number of unique values in X139
 The unique values are 2
Number of unique values in X140
 The unique values are 2
Number of unique values in X141
 The unique values are 2
Number of unique values in X142
 The unique values are 2
Number of unique values in X143
 The unique values are 2
Number of unique values in X144
 The unique values are 2
Number of unique values in X145
 The unique values are 2
Number of unique values in X146
 The unique values are 2
Number of unique values in X147
 The unique values are 2
Number of unique values in X148
 The unique values are 2
Number of unique values in X150
 The unique values are 2
Number of unique values in X151
 The unique values are 2
Number of unique values in X152
 The unique values are 2
Number of unique values in X153
 The unique values are 2
Number of unique values in X154
 The unique values are 2
Number of unique values in X155
 The unique values are 2
Number of unique values in X156
 The unique values are 2
Number of unique values in X157
 The unique values are 2
Number of unique values in X158
 The unique values are 2
Number of unique values in X159
 The unique values are 2
Number of unique values in X160
 The unique values are 2
Number of unique values in X161
 The unique values are 2
Number of unique values in X162
 The unique values are 2
Number of unique values in X163
 The unique values are 2
Number of unique values in X164
 The unique values are 2
Number of unique values in X165
 The unique values are 2
Number of unique values in X166
 The unique values are 2
Number of unique values in X167
 The unique values are 2
Number of unique values in X168
 The unique values are 2
Number of unique values in X169
 The unique values are 2
Number of unique values in X170
 The unique values are 2
Number of unique values in X171
 The unique values are 2
Number of unique values in X172
 The unique values are 2
Number of unique values in X173
 The unique values are 2
Number of unique values in X174
 The unique values are 2
Number of unique values in X175
 The unique values are 2
Number of unique values in X176
 The unique values are 2
Number of unique values in X177
 The unique values are 2
Number of unique values in X178
 The unique values are 2
Number of unique values in X179
 The unique values are 2
Number of unique values in X180
 The unique values are 2
Number of unique values in X181
 The unique values are 2
Number of unique values in X182
 The unique values are 2
Number of unique values in X183
 The unique values are 2
Number of unique values in X184
 The unique values are 2
Number of unique values in X185
 The unique values are 2
Number of unique values in X186
 The unique values are 2
Number of unique values in X187
 The unique values are 2
Number of unique values in X189
 The unique values are 2
Number of unique values in X190
 The unique values are 2
Number of unique values in X191
 The unique values are 2
Number of unique values in X192
 The unique values are 2
Number of unique values in X194
 The unique values are 2
Number of unique values in X195
 The unique values are 2
Number of unique values in X196
 The unique values are 2
Number of unique values in X197
 The unique values are 2
Number of unique values in X198
 The unique values are 2
Number of unique values in X199
 The unique values are 2
Number of unique values in X200
 The unique values are 2
Number of unique values in X201
 The unique values are 2
Number of unique values in X202
 The unique values are 2
Number of unique values in X203
 The unique values are 2
Number of unique values in X204
 The unique values are 2
Number of unique values in X205
 The unique values are 2
Number of unique values in X206
 The unique values are 2
Number of unique values in X207
 The unique values are 2
Number of unique values in X208
 The unique values are 2
Number of unique values in X209
 The unique values are 2
Number of unique values in X210
 The unique values are 2
Number of unique values in X211
 The unique values are 2
Number of unique values in X212
 The unique values are 2
Number of unique values in X213
 The unique values are 2
Number of unique values in X214
 The unique values are 2
Number of unique values in X215
 The unique values are 2
Number of unique values in X216
 The unique values are 2
Number of unique values in X217
 The unique values are 2
Number of unique values in X218
 The unique values are 2
Number of unique values in X219
 The unique values are 2
Number of unique values in X220
 The unique values are 2
Number of unique values in X221
 The unique values are 2
Number of unique values in X222
 The unique values are 2
Number of unique values in X223
 The unique values are 2
Number of unique values in X224
 The unique values are 2
Number of unique values in X225
 The unique values are 2
Number of unique values in X226
 The unique values are 2
Number of unique values in X227
 The unique values are 2
Number of unique values in X228
 The unique values are 2
Number of unique values in X229
 The unique values are 2
Number of unique values in X230
 The unique values are 2
Number of unique values in X231
 The unique values are 2
Number of unique values in X232
 The unique values are 2
Number of unique values in X233
 The unique values are 2
Number of unique values in X234
 The unique values are 2
Number of unique values in X235
 The unique values are 2
Number of unique values in X236
 The unique values are 2
Number of unique values in X237
 The unique values are 2
Number of unique values in X238
 The unique values are 2
Number of unique values in X239
 The unique values are 2
Number of unique values in X240
 The unique values are 2
Number of unique values in X241
 The unique values are 2
Number of unique values in X242
 The unique values are 2
Number of unique values in X243
 The unique values are 2
Number of unique values in X244
 The unique values are 2
Number of unique values in X245
 The unique values are 2
Number of unique values in X246
 The unique values are 2
Number of unique values in X247
 The unique values are 2
Number of unique values in X248
 The unique values are 2
Number of unique values in X249
 The unique values are 2
Number of unique values in X250
 The unique values are 2
Number of unique values in X251
 The unique values are 2
Number of unique values in X252
 The unique values are 2
Number of unique values in X253
 The unique values are 2
Number of unique values in X254
 The unique values are 2
Number of unique values in X255
 The unique values are 2
Number of unique values in X256
 The unique values are 2
Number of unique values in X257
 The unique values are 1
Number of unique values in X258
 The unique values are 1
Number of unique values in X259
 The unique values are 2
Number of unique values in X260
 The unique values are 2
Number of unique values in X261
 The unique values are 2
Number of unique values in X262
 The unique values are 2
Number of unique values in X263
 The unique values are 2
Number of unique values in X264
 The unique values are 2
Number of unique values in X265
 The unique values are 2
Number of unique values in X266
 The unique values are 2
Number of unique values in X267
 The unique values are 2
Number of unique values in X268
 The unique values are 2
Number of unique values in X269
 The unique values are 2
Number of unique values in X270
 The unique values are 2
Number of unique values in X271
 The unique values are 2
Number of unique values in X272
 The unique values are 2
Number of unique values in X273
 The unique values are 2
Number of unique values in X274
 The unique values are 2
Number of unique values in X275
 The unique values are 2
Number of unique values in X276
 The unique values are 2
Number of unique values in X277
 The unique values are 2
Number of unique values in X278
 The unique values are 2
Number of unique values in X279
 The unique values are 2
Number of unique values in X280
 The unique values are 2
Number of unique values in X281
 The unique values are 2
Number of unique values in X282
 The unique values are 2
Number of unique values in X283
 The unique values are 2
Number of unique values in X284
 The unique values are 2
Number of unique values in X285
 The unique values are 2
Number of unique values in X286
 The unique values are 2
Number of unique values in X287
 The unique values are 2
Number of unique values in X288
 The unique values are 2
Number of unique values in X289
 The unique values are 2
Number of unique values in X290
 The unique values are 2
Number of unique values in X291
 The unique values are 2
Number of unique values in X292
 The unique values are 2
Number of unique values in X293
 The unique values are 2
Number of unique values in X294
 The unique values are 2
Number of unique values in X295
 The unique values are 1
Number of unique values in X296
 The unique values are 1
Number of unique values in X297
 The unique values are 2
Number of unique values in X298
 The unique values are 2
Number of unique values in X299
 The unique values are 2
Number of unique values in X300
 The unique values are 2
Number of unique values in X301
 The unique values are 2
Number of unique values in X302
 The unique values are 2
Number of unique values in X304
 The unique values are 2
Number of unique values in X305
 The unique values are 2
Number of unique values in X306
 The unique values are 2
Number of unique values in X307
 The unique values are 2
Number of unique values in X308
 The unique values are 2
Number of unique values in X309
 The unique values are 2
Number of unique values in X310
 The unique values are 2
Number of unique values in X311
 The unique values are 2
Number of unique values in X312
 The unique values are 2
Number of unique values in X313
 The unique values are 2
Number of unique values in X314
 The unique values are 2
Number of unique values in X315
 The unique values are 2
Number of unique values in X316
 The unique values are 2
Number of unique values in X317
 The unique values are 2
Number of unique values in X318
 The unique values are 2
Number of unique values in X319
 The unique values are 2
Number of unique values in X320
 The unique values are 2
Number of unique values in X321
 The unique values are 2
Number of unique values in X322
 The unique values are 2
Number of unique values in X323
 The unique values are 2
Number of unique values in X324
 The unique values are 2
Number of unique values in X325
 The unique values are 2
Number of unique values in X326
 The unique values are 2
Number of unique values in X327
 The unique values are 2
Number of unique values in X328
 The unique values are 2
Number of unique values in X329
 The unique values are 2
Number of unique values in X330
 The unique values are 2
Number of unique values in X331
 The unique values are 2
Number of unique values in X332
 The unique values are 2
Number of unique values in X333
 The unique values are 2
Number of unique values in X334
 The unique values are 2
Number of unique values in X335
 The unique values are 2
Number of unique values in X336
 The unique values are 2
Number of unique values in X337
 The unique values are 2
Number of unique values in X338
 The unique values are 2
Number of unique values in X339
 The unique values are 2
Number of unique values in X340
 The unique values are 2
Number of unique values in X341
 The unique values are 2
Number of unique values in X342
 The unique values are 2
Number of unique values in X343
 The unique values are 2
Number of unique values in X344
 The unique values are 2
Number of unique values in X345
 The unique values are 2
Number of unique values in X346
 The unique values are 2
Number of unique values in X347
 The unique values are 2
Number of unique values in X348
 The unique values are 2
Number of unique values in X349
 The unique values are 2
Number of unique values in X350
 The unique values are 2
Number of unique values in X351
 The unique values are 2
Number of unique values in X352
 The unique values are 2
Number of unique values in X353
 The unique values are 2
Number of unique values in X354
 The unique values are 2
Number of unique values in X355
 The unique values are 2
Number of unique values in X356
 The unique values are 2
Number of unique values in X357
 The unique values are 2
Number of unique values in X358
 The unique values are 2
Number of unique values in X359
 The unique values are 2
Number of unique values in X360

In [17]:
n_f_c=list(train_data._get_numeric_data().columns)
n_f_c

['ID',
 'y',
 'X10',
 'X11',
 'X12',
 'X13',
 'X14',
 'X15',
 'X16',
 'X17',
 'X18',
 'X19',
 'X20',
 'X21',
 'X22',
 'X23',
 'X24',
 'X26',
 'X27',
 'X28',
 'X29',
 'X30',
 'X31',
 'X32',
 'X33',
 'X34',
 'X35',
 'X36',
 'X37',
 'X38',
 'X39',
 'X40',
 'X41',
 'X42',
 'X43',
 'X44',
 'X45',
 'X46',
 'X47',
 'X48',
 'X49',
 'X50',
 'X51',
 'X52',
 'X53',
 'X54',
 'X55',
 'X56',
 'X57',
 'X58',
 'X59',
 'X60',
 'X61',
 'X62',
 'X63',
 'X64',
 'X65',
 'X66',
 'X67',
 'X68',
 'X69',
 'X70',
 'X71',
 'X73',
 'X74',
 'X75',
 'X76',
 'X77',
 'X78',
 'X79',
 'X80',
 'X81',
 'X82',
 'X83',
 'X84',
 'X85',
 'X86',
 'X87',
 'X88',
 'X89',
 'X90',
 'X91',
 'X92',
 'X93',
 'X94',
 'X95',
 'X96',
 'X97',
 'X98',
 'X99',
 'X100',
 'X101',
 'X102',
 'X103',
 'X104',
 'X105',
 'X106',
 'X107',
 'X108',
 'X109',
 'X110',
 'X111',
 'X112',
 'X113',
 'X114',
 'X115',
 'X116',
 'X117',
 'X118',
 'X119',
 'X120',
 'X122',
 'X123',
 'X124',
 'X125',
 'X126',
 'X127',
 'X128',
 'X129',
 'X130',
 'X131',
 'X132',
 'X133',
 'X134',
 'X135',
 'X136',
 'X137',
 'X138',
 'X139',
 'X140',
 'X141',
 'X142',
 'X143',
 'X144',
 'X145',
 'X146',
 'X147',
 'X148',
 'X150',
 'X151',
 'X152',
 'X153',
 'X154',
 'X155',
 'X156',
 'X157',
 'X158',
 'X159',
 'X160',
 'X161',
 'X162',
 'X163',
 'X164',
 'X165',
 'X166',
 'X167',
 'X168',
 'X169',
 'X170',
 'X171',
 'X172',
 'X173',
 'X174',
 'X175',
 'X176',
 'X177',
 'X178',
 'X179',
 'X180',
 'X181',
 'X182',
 'X183',
 'X184',
 'X185',
 'X186',
 'X187',
 'X189',
 'X190',
 'X191',
 'X192',
 'X194',
 'X195',
 'X196',
 'X197',
 'X198',
 'X199',
 'X200',
 'X201',
 'X202',
 'X203',
 'X204',
 'X205',
 'X206',
 'X207',
 'X208',
 'X209',
 'X210',
 'X211',
 'X212',
 'X213',
 'X214',
 'X215',
 'X216',
 'X217',
 'X218',
 'X219',
 'X220',
 'X221',
 'X222',
 'X223',
 'X224',
 'X225',
 'X226',
 'X227',
 'X228',
 'X229',
 'X230',
 'X231',
 'X232',
 'X233',
 'X234',
 'X235',
 'X236',
 'X237',
 'X238',
 'X239',
 'X240',
 'X241',
 'X242',
 'X243',
 'X244',
 'X245',
 'X246',
 'X247',
 'X248',
 'X249',
 'X250',
 'X251',
 'X252',
 'X253',
 'X254',
 'X255',
 'X256',
 'X257',
 'X258',
 'X259',
 'X260',
 'X261',
 'X262',
 'X263',
 'X264',
 'X265',
 'X266',
 'X267',
 'X268',
 'X269',
 'X270',
 'X271',
 'X272',
 'X273',
 'X274',
 'X275',
 'X276',
 'X277',
 'X278',
 'X279',
 'X280',
 'X281',
 'X282',
 'X283',
 'X284',
 'X285',
 'X286',
 'X287',
 'X288',
 'X289',
 'X290',
 'X291',
 'X292',
 'X293',
 'X294',
 'X295',
 'X296',
 'X297',
 'X298',
 'X299',
 'X300',
 'X301',
 'X302',
 'X304',
 'X305',
 'X306',
 'X307',
 'X308',
 'X309',
 'X310',
 'X311',
 'X312',
 'X313',
 'X314',
 'X315',
 'X316',
 'X317',
 'X318',
 'X319',
 'X320',
 'X321',
 'X322',
 'X323',
 'X324',
 'X325',
 'X326',
 'X327',
 'X328',
 'X329',
 'X330',
 'X331',
 'X332',
 'X333',
 'X334',
 'X335',
 'X336',
 'X337',
 'X338',
 'X339',
 'X340',
 'X341',
 'X342',
 'X343',
 'X344',
 'X345',
 'X346',
 'X347',
 'X348',
 'X349',
 'X350',
 'X351',
 'X352',
 'X353',
 'X354',
 'X355',
 'X356',
 'X357',
 'X358',
 'X359',
 'X360',
 'X361',
 'X362',
 'X363',
 'X364',
 'X365',
 'X366',
 'X367',
 'X368',
 'X369',
 'X370',
 'X371',
 'X372',
 'X373',
 'X374',
 'X375',
 'X376',
 'X377',
 'X378',
 'X379',
 'X380',
 'X382',
 'X383',
 'X384',
 'X385']

In [18]:
c_f_c=list(set(train_data.columns)-set(train_data._get_numeric_data().columns))
c_f_c

['X5', 'X2', 'X6', 'X0', 'X4', 'X8', 'X1', 'X3']

In [19]:
n_f_c=list(test_data._get_numeric_data().columns)
n_f_c

['ID',
 'X10',
 'X11',
 'X12',
 'X13',
 'X14',
 'X15',
 'X16',
 'X17',
 'X18',
 'X19',
 'X20',
 'X21',
 'X22',
 'X23',
 'X24',
 'X26',
 'X27',
 'X28',
 'X29',
 'X30',
 'X31',
 'X32',
 'X33',
 'X34',
 'X35',
 'X36',
 'X37',
 'X38',
 'X39',
 'X40',
 'X41',
 'X42',
 'X43',
 'X44',
 'X45',
 'X46',
 'X47',
 'X48',
 'X49',
 'X50',
 'X51',
 'X52',
 'X53',
 'X54',
 'X55',
 'X56',
 'X57',
 'X58',
 'X59',
 'X60',
 'X61',
 'X62',
 'X63',
 'X64',
 'X65',
 'X66',
 'X67',
 'X68',
 'X69',
 'X70',
 'X71',
 'X73',
 'X74',
 'X75',
 'X76',
 'X77',
 'X78',
 'X79',
 'X80',
 'X81',
 'X82',
 'X83',
 'X84',
 'X85',
 'X86',
 'X87',
 'X88',
 'X89',
 'X90',
 'X91',
 'X92',
 'X93',
 'X94',
 'X95',
 'X96',
 'X97',
 'X98',
 'X99',
 'X100',
 'X101',
 'X102',
 'X103',
 'X104',
 'X105',
 'X106',
 'X107',
 'X108',
 'X109',
 'X110',
 'X111',
 'X112',
 'X113',
 'X114',
 'X115',
 'X116',
 'X117',
 'X118',
 'X119',
 'X120',
 'X122',
 'X123',
 'X124',
 'X125',
 'X126',
 'X127',
 'X128',
 'X129',
 'X130',
 'X131',
 'X132',
 'X133',
 'X134',
 'X135',
 'X136',
 'X137',
 'X138',
 'X139',
 'X140',
 'X141',
 'X142',
 'X143',
 'X144',
 'X145',
 'X146',
 'X147',
 'X148',
 'X150',
 'X151',
 'X152',
 'X153',
 'X154',
 'X155',
 'X156',
 'X157',
 'X158',
 'X159',
 'X160',
 'X161',
 'X162',
 'X163',
 'X164',
 'X165',
 'X166',
 'X167',
 'X168',
 'X169',
 'X170',
 'X171',
 'X172',
 'X173',
 'X174',
 'X175',
 'X176',
 'X177',
 'X178',
 'X179',
 'X180',
 'X181',
 'X182',
 'X183',
 'X184',
 'X185',
 'X186',
 'X187',
 'X189',
 'X190',
 'X191',
 'X192',
 'X194',
 'X195',
 'X196',
 'X197',
 'X198',
 'X199',
 'X200',
 'X201',
 'X202',
 'X203',
 'X204',
 'X205',
 'X206',
 'X207',
 'X208',
 'X209',
 'X210',
 'X211',
 'X212',
 'X213',
 'X214',
 'X215',
 'X216',
 'X217',
 'X218',
 'X219',
 'X220',
 'X221',
 'X222',
 'X223',
 'X224',
 'X225',
 'X226',
 'X227',
 'X228',
 'X229',
 'X230',
 'X231',
 'X232',
 'X233',
 'X234',
 'X235',
 'X236',
 'X237',
 'X238',
 'X239',
 'X240',
 'X241',
 'X242',
 'X243',
 'X244',
 'X245',
 'X246',
 'X247',
 'X248',
 'X249',
 'X250',
 'X251',
 'X252',
 'X253',
 'X254',
 'X255',
 'X256',
 'X257',
 'X258',
 'X259',
 'X260',
 'X261',
 'X262',
 'X263',
 'X264',
 'X265',
 'X266',
 'X267',
 'X268',
 'X269',
 'X270',
 'X271',
 'X272',
 'X273',
 'X274',
 'X275',
 'X276',
 'X277',
 'X278',
 'X279',
 'X280',
 'X281',
 'X282',
 'X283',
 'X284',
 'X285',
 'X286',
 'X287',
 'X288',
 'X289',
 'X290',
 'X291',
 'X292',
 'X293',
 'X294',
 'X295',
 'X296',
 'X297',
 'X298',
 'X299',
 'X300',
 'X301',
 'X302',
 'X304',
 'X305',
 'X306',
 'X307',
 'X308',
 'X309',
 'X310',
 'X311',
 'X312',
 'X313',
 'X314',
 'X315',
 'X316',
 'X317',
 'X318',
 'X319',
 'X320',
 'X321',
 'X322',
 'X323',
 'X324',
 'X325',
 'X326',
 'X327',
 'X328',
 'X329',
 'X330',
 'X331',
 'X332',
 'X333',
 'X334',
 'X335',
 'X336',
 'X337',
 'X338',
 'X339',
 'X340',
 'X341',
 'X342',
 'X343',
 'X344',
 'X345',
 'X346',
 'X347',
 'X348',
 'X349',
 'X350',
 'X351',
 'X352',
 'X353',
 'X354',
 'X355',
 'X356',
 'X357',
 'X358',
 'X359',
 'X360',
 'X361',
 'X362',
 'X363',
 'X364',
 'X365',
 'X366',
 'X367',
 'X368',
 'X369',
 'X370',
 'X371',
 'X372',
 'X373',
 'X374',
 'X375',
 'X376',
 'X377',
 'X378',
 'X379',
 'X380',
 'X382',
 'X383',
 'X384',
 'X385']

In [20]:
c_f_c=list(set(test_data.columns)-set(test_data._get_numeric_data().columns))
c_f_c

['X5', 'X2', 'X6', 'X0', 'X4', 'X8', 'X1', 'X3']

In [21]:
le_x2=LabelEncoder()
le_x1=LabelEncoder()
le_x3=LabelEncoder()
le_x0=LabelEncoder()
le_x8=LabelEncoder()
le_x4=LabelEncoder()
le_x5=LabelEncoder()
le_x6=LabelEncoder()
train_data['X0']=le_x0.fit_transform(train_data['X0'])
train_data['X2']=le_x2.fit_transform(train_data['X2'])
train_data['X1']=le_x1.fit_transform(train_data['X1'])
train_data['X3']=le_x3.fit_transform(train_data['X3'])
train_data['X4']=le_x4.fit_transform(train_data['X4'])
train_data['X5']=le_x5.fit_transform(train_data['X5'])
train_data['X6']=le_x6.fit_transform(train_data['X6'])
train_data['X8']=le_x8.fit_transform(train_data['X8'])

test_data['X0']=le_x0.fit_transform(test_data['X0'])
test_data['X2']=le_x2.fit_transform(test_data['X2'])
test_data['X1']=le_x1.fit_transform(test_data['X1'])
test_data['X3']=le_x3.fit_transform(test_data['X3'])
test_data['X4']=le_x4.fit_transform(test_data['X4'])
test_data['X5']=le_x5.fit_transform(test_data['X5'])
test_data['X6']=le_x6.fit_transform(test_data['X6'])
test_data['X8']=le_x8.fit_transform(test_data['X8'])
train_data.head()

,ID,y,X0,X1,X2,X3,X4,X5,X6,X8,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
0,0,130.81,32,23,17,0,3,24,9,14,...,0,0,1,0,0,0,0,0,0,0
1,6,88.53,32,21,19,4,3,28,11,14,...,1,0,0,0,0,0,0,0,0,0
2,7,76.26,20,24,34,2,3,27,9,23,...,0,0,0,0,0,0,1,0,0,0
3,9,80.62,20,21,34,5,3,27,11,4,...,0,0,0,0,0,0,0,0,0,0
4,13,78.02,20,23,34,5,3,12,3,13,...,0,0,0,0,0,0,0,0,0,0

In [22]:
test_data.head()

,ID,X0,X1,X2,X3,X4,X5,X6,X8,X10,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
0,1,21,23,34,5,3,26,0,22,0,...,0,0,0,1,0,0,0,0,0,0
1,2,42,3,8,0,3,9,6,24,0,...,0,0,1,0,0,0,0,0,0,0
2,3,21,23,17,5,3,0,9,9,0,...,0,0,0,1,0,0,0,0,0,0
3,4,21,13,34,5,3,31,11,13,0,...,0,0,0,1,0,0,0,0,0,0
4,5,45,20,17,2,3,30,8,12,0,...,1,0,0,0,0,0,0,0,0,0

In [23]:
new_train_data=pd.concat([train_data],axis=1)
new_train_data.head()

,ID,y,X0,X1,X2,X3,X4,X5,X6,X8,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
0,0,130.81,32,23,17,0,3,24,9,14,...,0,0,1,0,0,0,0,0,0,0
1,6,88.53,32,21,19,4,3,28,11,14,...,1,0,0,0,0,0,0,0,0,0
2,7,76.26,20,24,34,2,3,27,9,23,...,0,0,0,0,0,0,1,0,0,0
3,9,80.62,20,21,34,5,3,27,11,4,...,0,0,0,0,0,0,0,0,0,0
4,13,78.02,20,23,34,5,3,12,3,13,...,0,0,0,0,0,0,0,0,0,0

In [24]:
new_test_data=pd.concat([test_data],axis=1)
new_test_data.head()

,ID,X0,X1,X2,X3,X4,X5,X6,X8,X10,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
0,1,21,23,34,5,3,26,0,22,0,...,0,0,0,1,0,0,0,0,0,0
1,2,42,3,8,0,3,9,6,24,0,...,0,0,1,0,0,0,0,0,0,0
2,3,21,23,17,5,3,0,9,9,0,...,0,0,0,1,0,0,0,0,0,0
3,4,21,13,34,5,3,31,11,13,0,...,0,0,0,1,0,0,0,0,0,0
4,5,45,20,17,2,3,30,8,12,0,...,1,0,0,0,0,0,0,0,0,0

In [25]:
features=new_train_data.drop(['y'],axis=1)
target=new_train_data[['y']]
X_train,X_test,y_train,y_test=train_test_split(features,target,train_size=0.85,random_state=5)
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(3577, 377)
(632, 377)
(3577, 1)
(632, 1)

In [26]:
my_model=LinearRegression()
my_model.fit(X_train,y_train)
predictions=my_model.predict(X_test)
predictions_train=my_model.predict(X_train)
print('MSE:',mean_squared_error(predictions,y_test))
print('RMSE:',np.sqrt(mean_squared_error(predictions,y_test)))
print('r2_score on test data:',r2_score(predictions,y_test))
print('r2_score on train data:',r2_score(predictions_train,y_train))

MSE: 77.50831247231706
RMSE: 8.803880534873077
r2_score on test data: 0.20225527583484926
r2_score on train data: 0.28945566962249714

In [27]:
my_model.predict(new_test_data)

array([[ 76.7315957 ],
       [120.0365375 ],
       [ 79.66042623],
       ...,
       [ 93.23628601],
       [108.93186882],
       [ 93.12977787]])

In [28]:
pd.concat([new_test_data,pd.DataFrame(my_model.predict(new_test_data))],axis=1).to_csv('final_val.csv',index=False)

In [29]:
my_model=Ridge(alpha=5)
my_model.fit(X_train,y_train)
predictions=my_model.predict(X_test)
print('MSE:',mean_squared_error(predictions,y_test))
print('RMSE',np.sqrt(mean_squared_error(predictions,y_test)))
print('r2_score:',r2_score(predictions,y_test))

MSE: 73.21210461895993
RMSE 8.556407226106055
r2_score: 0.23246031872899853

In [30]:
my_model=Lasso()
my_model.fit(X_train,y_train)
predcitions=my_model.predict(X_test)
print('MSE:',mean_squared_error(predictions,y_test))
print('RMSE',np.sqrt(mean_squared_error(predictions,y_test)))
print('r2_score:',r2_score(predictions,y_test))

MSE: 73.21210461895993
RMSE 8.556407226106055
r2_score: 0.23246031872899853

In [31]:
my_model=ElasticNet()
my_model.fit(X_train,y_train)
predictions=my_model.predict(X_test)
print('MSE:',mean_squared_error(predictions,y_test))
print('RMSE',np.sqrt(mean_squared_error(predictions,y_test)))

MSE: 102.76924069338156
RMSE 10.137516495344487

In [32]:
pca=PCA(n_components=0.95)
pca.fit(X_train)

PCA(n_components=0.95)

In [33]:
pca.explained_variance_ratio_

array([0.99991518])

In [34]:
pca.explained_variance_ratio_.shape

(1,)

In [35]:
np.sum(pca.explained_variance_ratio_)

0.9999151787673826

In [36]:
X_train_transformed=pca.transform(X_train)
X_test_transformed=pca.transform(X_test)
pd.DataFrame(X_train_transformed)

                0
0     2827.932514
1      476.927205
2    -2550.083728
3     3712.944129
4      215.923757
...           ...
3572  1911.934739
3573  -751.095087
3574  3967.926515
3575   318.927710
3576  1641.934490

[3577 rows x 1 columns]

In [37]:
X_train_transformed.shape,X_test_transformed.shape

((3577, 1), (632, 1))

In [38]:
pca.inverse_transform(X_train_transformed).shape

(3577, 377)

In [39]:
my_model.fit(X_train_transformed,y_train)
preds=my_model.predict(X_test_transformed)
print(r2_score(y_test,preds))

0.005985842067077307

In [40]:
X=X_train_transformed

In [41]:
y=y_train

In [42]:
my_model=XGBRegressor()
my_model=XGBRegressor(n_estimators=1000,max_depth=7,eta=0.1,subsample=0.7,colsample_bytree=0.8)
cv=RepeatedKFold(n_splits=10,n_repeats=3,random_state=1)
scores=cross_val_score(my_model,X,y,scoring='neg_mean_absolute_error',cv=cv,n_jobs=-1)
scores=absolute(scores)
print('Mean MAE:%.3f(%.3f)'%(scores.mean(),scores.std()))

Mean MAE:13.005(0.484)

In [43]:
X=X_test_transformed

In [44]:
y=y_test

In [45]:
my_model.fit(X,y)

XGBRegressor(base_score=0.5, booster=None, colsample_bylevel=1,
             colsample_bynode=1, colsample_bytree=0.8, eta=0.1, gamma=0,
             gpu_id=-1, importance_type='gain', interaction_constraints=None,
             learning_rate=0.100000001, max_delta_step=0, max_depth=7,
             min_child_weight=1, missing=nan, monotone_constraints=None,
             n_estimators=1000, n_jobs=0, num_parallel_tree=1, random_state=0,
             reg_alpha=0, reg_lambda=1, scale_pos_weight=1, subsample=0.7,
             tree_method=None, validate_parameters=False, verbosity=None)

In [46]:
yhat=my_model.predict(y)
print('Predicted:%.3f' %yhat)

ValueError: feature_names mismatch: ['f0'] ['y']
expected f0 in input data
training data did not have the following fields: y